// Page content for every landing page. Copy matches the live lp.fielmente.com pages.
// To add a page: add an entry here, then link it from content/site.ts if it belongs in the footer.
import type { LandingPage, PartnersSection } from "./types";

export const BUSINESS_PARTNERS: PartnersSection = {
  type: "partners",
  label: "Our business partners",
  logos: [
    { src: "/images/partners/google-partner.png", alt: "Google Partner", height: 42 },
    { src: "/images/partners/meta-business-partner.png", alt: "Meta Business Partner", height: 42 },
    { src: "/images/partners/booking-com.png", alt: "Booking.com", height: 28 },
    { src: "/images/partners/agoda-logo.png", alt: "Agoda", height: 34 },
    { src: "/images/partners/airbnb-logo.png", alt: "Airbnb", height: 32 },
    { src: "/images/partners/makemytrip-logo.png", alt: "MakeMyTrip", height: 28 },
    { src: "/images/partners/goibibo-logo.png", alt: "Goibibo", height: 28 },
    { src: "/images/partners/cleartrip-logo.png", alt: "Cleartrip", height: 24 },
    { src: "/images/partners/razorpay.png", alt: "Razorpay", height: 28 },
    { src: "/images/partners/zoho-corporation.png", alt: "Zoho", height: 32 },
    { src: "/images/partners/aws.png", alt: "AWS", height: 32 },
  ],
};

export const pages: LandingPage[] = [
  {
    slug: "resort",
    title: "Resort Marketing Agency — Ads, SEO, OTA & Revenue | Fielmente",
    description: "Resort marketing agency for direct bookings: Google & Meta Ads, SEO, websites, OTA and revenue management. Free resort audit.",
    waTopic: "Resort Marketing",
    headerCta: "Free audit",
    mobileCta: "Get free audit",
    hero: {
      image: "/images/photos/im7.webp",
      tag: "Resort Marketing Agency",
      title: "Fill every season with ",
      titleAccent: "direct bookings.",
      subtitle: "Resort digital marketing, SEO, OTAs and revenue management.",
      chips: ["+30–50% bookings", "2.4× avg. ROAS", "120+ hotels & resorts"],
      form: { title: "Get a free resort audit", button: "Get my free audit" },
    },
    sections: [
      BUSINESS_PARTNERS,
      {
        type: "gallery",
        eyebrow: "Every kind of stay",
        title: "Resorts, glamping, villas and homestays",
        layout: "default",
        items: [
          { src: "/images/photos/im7.webp", alt: "Resorts", caption: "Resorts" },
          { src: "/images/photos/im3.webp", alt: "Glamping", caption: "Glamping" },
          { src: "/images/photos/im4.webp", alt: "Villas", caption: "Villas" },
          { src: "/images/photos/im6.webp", alt: "Homestays", caption: "Homestays" },
        ],
        cta: "Get my free resort audit",
      },
      {
        type: "services",
        tone: "alt",
        eyebrow: "What we do",
        title: "Everything you need to book direct",
        text: "Tap any service to get a free audit.",
        items: [
          {
            image: "/images/services/hotel-website-development.png",
            title: "Website & Booking Engine",
            note: "+30% direct reservations in 60 days",
            muted: false,
          },
          {
            image: "/images/services/performance-marketing.png",
            title: "Google & Meta Ads",
            note: "Avg. 2.4× ROAS",
            muted: false,
          },
          {
            image: "/images/services/seo-for-hotel.png",
            title: "SEO & Local SEO",
            note: "Top 3 in 90 days (avg.)",
            muted: false,
          },
          {
            image: "/images/services/ota-management.png",
            title: "OTA Management",
            note: "Listings, parity, ranking",
            muted: true,
          },
          {
            image: "/images/photos/grilwithchart.webp",
            title: "Revenue Management",
            note: "Right rate, every night",
            muted: true,
          },
          {
            image: "/images/services/social-media-management.png",
            title: "Social Media & Content",
            note: "Reels, shoots, community",
            muted: true,
          },
        ],
        eazotel: true,
      },
      { type: "steps" },
      {
        type: "stats",
        stats: [
          { value: "500+", label: "properties served", countUp: true },
          { value: "+38%", label: "avg. direct revenue lift", countUp: true },
          { value: "95%", label: "client retention", countUp: true },
          { value: "4.8★", label: "client satisfaction", countUp: true },
        ],
        cta: "Grow my resort",
      },
      {
        type: "clients",
        eyebrow: "Our clients",
        title: "Resorts that grow with us",
        rows: [
          [
            { src: "/images/clients/arkaya.png", alt: "Arkaya" },
            { src: "/images/clients/wabi-sabi.jpg", alt: "Wabi Sabi" },
            { src: "/images/clients/naad-wellness.png", alt: "Naad Wellness" },
            { src: "/images/clients/naturoville.png", alt: "Naturoville" },
            { src: "/images/clients/corbett-the-grand.png", alt: "Corbett The Grand" },
            { src: "/images/clients/north-wind.png", alt: "North Wind" },
            { src: "/images/clients/colonels-resort.png", alt: "Colonel's Resort" },
            { src: "/images/clients/grandview-resort.jpg", alt: "Grandview Resort" },
            { src: "/images/clients/kumaon-bliss.jpg", alt: "Kumaon Bliss" },
          ],
          [
            { src: "/images/clients/eracamp.png", alt: "Era Camp" },
            { src: "/images/clients/tents-and-trails.png", alt: "Tents & Trails" },
            { src: "/images/clients/nature-on-the-rocks.webp", alt: "Nature on the Rocks" },
            { src: "/images/clients/dunagiri-logo-square.png", alt: "Dunagiri" },
            { src: "/images/clients/emeraldtrail.png", alt: "Emerald Trail" },
            { src: "/images/clients/lakehill.png", alt: "Lake Hill" },
            { src: "/images/clients/la-mount.webp", alt: "La Mount" },
            { src: "/images/clients/riviera.jpg", alt: "Riviera" },
            { src: "/images/clients/red-rock-villa.jpg", alt: "Red Rock Villa" },
          ],
        ],
        cta: "Join 120+ hotels & resorts",
      },
    ],
    finalImage: "/images/photos/im4.webp",
  },
  {
    slug: "hotel",
    title: "Hotel Marketing Company — Grow Bookings 30–50% | Fielmente",
    description: "Hotel marketing company: Google & Meta Ads, SEO, OTA and revenue management, WhatsApp marketing and branding. Grow bookings 30–50%.",
    waTopic: "Hotel Marketing",
    headerCta: "Free consultation",
    mobileCta: "Free consultation",
    hero: {
      image: "/images/photos/hotel-1.webp",
      tag: "Hotel Marketing Company",
      title: "Grow direct & OTA bookings by ",
      titleAccent: "30–50%.",
      subtitle: "Ads, SEO, OTAs, revenue management and WhatsApp marketing.",
      chips: ["+38% direct revenue", "95% retention", "India · UAE · UK"],
      form: { title: "Get a FREE consultation", button: "Get my free consultation" },
    },
    sections: [
      BUSINESS_PARTNERS,
      {
        type: "gallery",
        eyebrow: "Every room, sold direct",
        title: "More bookings for every part of your hotel",
        layout: "default",
        items: [
          { src: "/images/photos/hotel-3.webp", alt: "Rooms", caption: "Rooms" },
          { src: "/images/services/about2.jpg", alt: "Experiences", caption: "Experiences" },
          { src: "/images/photos/hotel-4.webp", alt: "Guests", caption: "Guests" },
          { src: "/images/photos/hotel-2.webp", alt: "Direct bookings", caption: "Direct bookings" },
        ],
        cta: "Get my free consultation",
      },
      {
        type: "services",
        tone: "alt",
        eyebrow: "What we do",
        title: "Everything you need to book direct",
        text: "Tap any service to get a free audit.",
        items: [
          {
            image: "/images/services/hotel-website-development.png",
            title: "Website & Booking Engine",
            note: "+30% direct reservations in 60 days",
            muted: false,
          },
          {
            image: "/images/services/performance-marketing.png",
            title: "Google & Meta Ads",
            note: "Avg. 2.4× ROAS",
            muted: false,
          },
          {
            image: "/images/services/local-seo.png",
            title: "SEO & Google Maps",
            note: "Top 3 in 90 days (avg.)",
            muted: false,
          },
          {
            image: "/images/services/ota-management.png",
            title: "OTA Management",
            note: "Listings, parity, ranking",
            muted: true,
          },
          {
            image: "/images/photos/grilwithchart.webp",
            title: "Revenue Management",
            note: "Right rate, every night",
            muted: true,
          },
          {
            image: "/images/photos/built-ai.png",
            title: "WhatsApp AI & Hotel CRM",
            note: "Every enquiry answered 24/7",
            muted: true,
          },
          {
            image: "/images/services/social-media-management.png",
            title: "Social Media & Content",
            note: "Reels, shoots, community",
            muted: true,
          },
        ],
        eazotel: true,
      },
      { type: "steps" },
      {
        type: "stats",
        stats: [
          { value: "500+", label: "properties served", countUp: true },
          { value: "1,000+", label: "campaigns delivered", countUp: true },
          { value: "+38%", label: "avg. direct revenue lift", countUp: true },
          { value: "4.8★", label: "client satisfaction", countUp: true },
        ],
        cta: "Grow my hotel",
      },
      {
        type: "clients",
        eyebrow: "Our clients",
        title: "Hotels that grow with us",
        rows: [
          [
            { src: "/images/clients/hotel-green-castle.jpg", alt: "Hotel Green Castle" },
            { src: "/images/clients/zionhotel.png", alt: "Zion Hotel" },
            { src: "/images/clients/hotel-awadha-vilas.webp", alt: "Hotel Awadha Vilas" },
            { src: "/images/clients/hotel-platinum-shravasti.png", alt: "Hotel Platinum Shravasti" },
            { src: "/images/clients/mahabir-palace.png", alt: "Mahabir Palace" },
            { src: "/images/clients/soni-arena-hotel.png", alt: "Soni Arena Hotel" },
            { src: "/images/clients/tulipinn.png", alt: "Tulip Inn" },
            { src: "/images/clients/season-suites.png", alt: "Season Suites" },
            { src: "/images/clients/anandha-inn.webp", alt: "Anandha Inn" },
          ],
          [
            { src: "/images/clients/miramar-logo.jpg", alt: "Miramar" },
            { src: "/images/clients/umaid2.png", alt: "Umaid" },
            { src: "/images/clients/allure-nainital-logo.png", alt: "Allure Nainital" },
            { src: "/images/clients/altin-stays.webp", alt: "Altin Stays" },
            { src: "/images/clients/infinity.webp", alt: "Infinity" },
            { src: "/images/clients/nothern-nawab.webp", alt: "Northern Nawab" },
            { src: "/images/clients/stone-hedge.webp", alt: "Stone Hedge" },
            { src: "/images/clients/opera-house.png", alt: "Opera House" },
            { src: "/images/clients/one-off.png", alt: "One Off" },
          ],
        ],
        cta: "Join 120+ hotels & resorts",
      },
    ],
    finalImage: "/images/services/about2.jpg",
  },
  {
    slug: "hospitality",
    title: "Hospitality Marketing Agency in India | Fielmente",
    description: "Marketing for hotels, resorts, homestays, villas, glamping, cafés and restaurants. 500+ brands since 2020.",
    waTopic: "Hospitality Marketing",
    headerCta: "Free consultation",
    mobileCta: "Free consultation",
    hero: {
      image: "/images/photos/im8.webp",
      tag: "Hospitality Marketing Agency",
      title: "More guests for ",
      titleAccent: "every hospitality business.",
      subtitle: "Hotels · Resorts · Homestays · Villas · Glamping · Cafés · Restaurants",
      chips: ["500+ brands since 2020", "1,000+ campaigns", "Sales & marketing automation"],
      form: { title: "Get a FREE consultation", button: "Get my free consultation" },
    },
    sections: [
      BUSINESS_PARTNERS,
      {
        type: "gallery",
        eyebrow: "Industries we grow",
        title: "Built for every kind of hospitality business",
        layout: "default",
        items: [
          { src: "/images/photos/im8.webp", alt: "Hotels", caption: "Hotels" },
          { src: "/images/photos/im7.webp", alt: "Resorts", caption: "Resorts" },
          { src: "/images/photos/im6.webp", alt: "Homestays", caption: "Homestays" },
          { src: "/images/photos/im5.webp", alt: "Airbnbs", caption: "Airbnbs" },
          { src: "/images/photos/im4.webp", alt: "Villas", caption: "Villas" },
          { src: "/images/photos/im3.webp", alt: "Glamping", caption: "Glamping" },
          { src: "/images/photos/im2.webp", alt: "Cafés", caption: "Cafés" },
          { src: "/images/photos/im1.webp", alt: "Restaurants", caption: "Restaurants" },
        ],
        cta: "Get my free consultation",
      },
      {
        type: "services",
        tone: "alt",
        eyebrow: "What we do",
        title: "Everything you need to book direct",
        text: "Tap any service to get a free audit.",
        items: [
          {
            image: "/images/services/hotel-website-development.png",
            title: "Website & Booking Engine",
            note: "+30% direct reservations in 60 days",
            muted: false,
          },
          {
            image: "/images/services/performance-marketing.png",
            title: "Google & Meta Ads",
            note: "Avg. 2.4× ROAS",
            muted: false,
          },
          {
            image: "/images/services/seo-for-hotel.png",
            title: "SEO & Local SEO",
            note: "Top 3 in 90 days (avg.)",
            muted: false,
          },
          {
            image: "/images/services/social-media-management.png",
            title: "Social Media & Content",
            note: "Reels, shoots, community",
            muted: true,
          },
          {
            image: "/images/services/ota-management.png",
            title: "OTA Management",
            note: "Listings, parity, ranking",
            muted: true,
          },
          {
            image: "/images/photos/grilwithchart.webp",
            title: "Revenue Management",
            note: "Right rate, every night",
            muted: true,
          },
        ],
        eazotel: true,
      },
      { type: "steps" },
      {
        type: "stats",
        stats: [
          { value: "500+", label: "properties served", countUp: true },
          { value: "1,000+", label: "campaigns delivered", countUp: true },
          { value: "95%", label: "client retention", countUp: true },
          { value: "4.8★", label: "client satisfaction", countUp: true },
        ],
        cta: "Grow my business",
      },
      {
        type: "map",
        eyebrow: "Where we work",
        title: "India, UAE & UK. Since 2020.",
        text: "500+ hospitality brands across three countries.",
        cta: "Talk to our team",
        image: { src: "/images/map-base.png", alt: "Countries Fielmente has worked in" },
      },
      {
        type: "clients",
        eyebrow: "Our clients",
        title: "Brands that grow with us",
        rows: [
          [
            { src: "/images/clients/arkaya.png", alt: "Arkaya" },
            { src: "/images/clients/wabi-sabi.jpg", alt: "Wabi Sabi" },
            { src: "/images/clients/corbett-the-grand.png", alt: "Corbett The Grand" },
            { src: "/images/clients/naad-wellness.png", alt: "Naad Wellness" },
            { src: "/images/clients/hotel-green-castle.jpg", alt: "Hotel Green Castle" },
            { src: "/images/clients/zionhotel.png", alt: "Zion Hotel" },
            { src: "/images/clients/mahabir-palace.png", alt: "Mahabir Palace" },
            { src: "/images/clients/park-cafe.png", alt: "Park Cafe" },
          ],
          [
            { src: "/images/clients/chocolate-room.png", alt: "The Chocolate Room" },
            { src: "/images/clients/chefkenzo.png", alt: "Chef Kenzo" },
            { src: "/images/clients/eastrenspice.webp", alt: "Eastern Spice" },
            { src: "/images/clients/spice-haven.png", alt: "Spice Haven" },
            { src: "/images/clients/petal-panyaram.png", alt: "Petals & Paniyaram" },
            { src: "/images/clients/north-wind.png", alt: "North Wind" },
            { src: "/images/clients/eracamp.png", alt: "Era Camp" },
            { src: "/images/clients/nothern-nawab.webp", alt: "Northern Nawab" },
          ],
        ],
        cta: "Join 500+ brands",
      },
    ],
    finalImage: "/images/photos/im1.webp",
  },
  {
    slug: "google-ads",
    title: "Google & Meta Ads for Hotels & Resorts | Fielmente",
    description: "Hotel and resort ads that fill rooms. Avg. 2.4× ROAS. Google Partner and Meta Business Partner.",
    waTopic: "Google & Meta Ads",
    headerCta: "Free audit",
    mobileCta: "Get free audit",
    hero: {
      image: "/images/services/performance-marketing.png",
      tag: "Google & Meta Ads",
      title: "Ads that fill rooms, ",
      titleAccent: "not just clicks.",
      subtitle: "High-ROI campaigns that drive direct bookings.",
      chips: ["Avg. 2.4× ROAS", "1,000+ campaigns"],
      badges: [
        { src: "/images/partners/google-partner.png", alt: "Google Partner" },
        { src: "/images/partners/meta-business-partner.png", alt: "Meta Business Partner" },
      ],
      form: { title: "Get a free ads audit", button: "Get my free audit" },
    },
    sections: [
      BUSINESS_PARTNERS,
      {
        type: "split",
        tone: "alt",
        image: { src: "/images/photos/hotel-2.webp", alt: "Booking on a tablet" },
        eyebrow: "What you get",
        title: "Every rupee working for bookings",
        features: [
          { title: "Google Search ads", text: "Catch ready-to-book travellers." },
          { title: "Instagram & Facebook", text: "Inspire the next trip." },
          { title: "Retargeting", text: "Win back lost visitors." },
          { title: "Booking tracking", text: "Spend tied to revenue." },
        ],
        cta: "Get my free ads audit",
      },
      { type: "steps" },
      {
        type: "stats",
        stats: [
          { value: "2.4×", label: "avg. ROAS", countUp: true },
          { value: "1,000+", label: "campaigns delivered", countUp: true },
          { value: "500+", label: "properties served", countUp: true },
          { value: "95%", label: "client retention", countUp: true },
        ],
        cta: "Get these results",
      },
      {
        type: "clients",
        eyebrow: "Our clients",
        title: "Trusted by 120+ hotels & resorts",
        rows: [
          [
            { src: "/images/clients/arkaya.png", alt: "Arkaya" },
            { src: "/images/clients/wabi-sabi.jpg", alt: "Wabi Sabi" },
            { src: "/images/clients/naad-wellness.png", alt: "Naad Wellness" },
            { src: "/images/clients/corbett-the-grand.png", alt: "Corbett The Grand" },
            { src: "/images/clients/north-wind.png", alt: "North Wind" },
            { src: "/images/clients/naturoville.png", alt: "Naturoville" },
          ],
          [
            { src: "/images/clients/hotel-green-castle.jpg", alt: "Hotel Green Castle" },
            { src: "/images/clients/zionhotel.png", alt: "Zion Hotel" },
            { src: "/images/clients/mahabir-palace.png", alt: "Mahabir Palace" },
            { src: "/images/clients/soni-arena-hotel.png", alt: "Soni Arena Hotel" },
            { src: "/images/clients/kumaon-bliss.jpg", alt: "Kumaon Bliss" },
            { src: "/images/clients/colonels-resort.png", alt: "Colonel's Resort" },
          ],
        ],
        cta: "Join them",
      },
    ],
    finalImage: "/images/photos/im7.webp",
  },
  {
    slug: "seo",
    title: "Hotel SEO & Local SEO Agency | Fielmente",
    description: "Rank on Google and Google Maps. Top 3 in 90 days on average. Free SEO audit.",
    waTopic: "Hotel SEO",
    headerCta: "Free audit",
    mobileCta: "Get free audit",
    hero: {
      image: "/images/photos/im8.webp",
      tag: "SEO & Local SEO",
      title: "Rank on Google. ",
      titleAccent: "Get booked direct.",
      subtitle: "Be found on Search and Google Maps.",
      chips: ["Top 3 in 90 days (avg.)", "2× more calls from Maps"],
      form: { title: "Get a free SEO audit", button: "Get my free audit" },
    },
    sections: [
      BUSINESS_PARTNERS,
      {
        type: "gallery",
        tone: "alt",
        eyebrow: "What you get",
        title: "Found on Search. Found on Maps.",
        layout: "duo",
        items: [
          {
            src: "/images/services/seo-for-hotel.png",
            alt: "Google Search",
            caption: "Google Search",
            wide: true,
          },
          { src: "/images/services/local-seo.png", alt: "Google Maps", caption: "Google Maps", wide: true },
        ],
        features: [
          { title: "Keyword research", text: "What your guests search." },
          { title: "On-page & technical", text: "A fast, crawlable site." },
          { title: "Google Business Profile", text: "Win “near me”." },
          { title: "Content & blogs", text: "Pages that rank." },
        ],
        cta: "Get my free SEO audit",
      },
      { type: "steps" },
      {
        type: "stats",
        stats: [
          { value: "Top 3", label: "in 90 days on average", countUp: true },
          { value: "2×", label: "more calls & enquiries", countUp: true },
          { value: "500+", label: "properties served", countUp: true },
          { value: "95%", label: "client retention", countUp: true },
        ],
        cta: "Get these results",
      },
      {
        type: "clients",
        eyebrow: "Our clients",
        title: "Trusted by 120+ hotels & resorts",
        rows: [
          [
            { src: "/images/clients/arkaya.png", alt: "Arkaya" },
            { src: "/images/clients/wabi-sabi.jpg", alt: "Wabi Sabi" },
            { src: "/images/clients/naad-wellness.png", alt: "Naad Wellness" },
            { src: "/images/clients/corbett-the-grand.png", alt: "Corbett The Grand" },
            { src: "/images/clients/north-wind.png", alt: "North Wind" },
            { src: "/images/clients/naturoville.png", alt: "Naturoville" },
          ],
          [
            { src: "/images/clients/hotel-green-castle.jpg", alt: "Hotel Green Castle" },
            { src: "/images/clients/zionhotel.png", alt: "Zion Hotel" },
            { src: "/images/clients/mahabir-palace.png", alt: "Mahabir Palace" },
            { src: "/images/clients/soni-arena-hotel.png", alt: "Soni Arena Hotel" },
            { src: "/images/clients/kumaon-bliss.jpg", alt: "Kumaon Bliss" },
            { src: "/images/clients/colonels-resort.png", alt: "Colonel's Resort" },
          ],
        ],
        cta: "Join them",
      },
    ],
    finalImage: "/images/photos/hotel-3.webp",
  },
  {
    slug: "social-media",
    title: "Social Media Management for Hotels & Resorts | Fielmente",
    description: "Instagram and Facebook content, reels and shoots for hospitality brands.",
    waTopic: "Social Media Management",
    headerCta: "Free review",
    mobileCta: "Get free review",
    hero: {
      image: "/images/photos/high-angle.jpg",
      tag: "Social Media Management",
      title: "An Instagram that makes people ",
      titleAccent: "want to stay.",
      subtitle: "Strategy, content and community.",
      chips: ["Reels & shoots", "Instagram & Facebook"],
      badges: [
        { src: "/images/partners/meta-business-partner.png", alt: "Meta Business Partner" },
      ],
      form: { title: "Get a free profile review", button: "Review my profile" },
    },
    sections: [
      BUSINESS_PARTNERS,
      {
        type: "gallery",
        tone: "alt",
        eyebrow: "What you get",
        title: "Content that sells the stay",
        layout: "default",
        items: [
          { src: "/images/photos/im7.webp", alt: "Resort post" },
          { src: "/images/photos/im2.webp", alt: "Café post" },
          { src: "/images/photos/im3.webp", alt: "Glamping post" },
          { src: "/images/photos/im1.webp", alt: "Restaurant post" },
        ],
        features: [
          { title: "Content calendar", text: "Planned around your season." },
          { title: "Reels & creatives", text: "Scroll-stopping, on-brand." },
          { title: "Property shoots", text: "Photos & video." },
          { title: "Community", text: "DMs into enquiries." },
        ],
        cta: "Review my profile",
      },
      { type: "steps", cta: "Start with a free review" },
      {
        type: "stats",
        stats: [
          { value: "500+", label: "brands since 2020", countUp: true },
          { value: "1,000+", label: "campaigns delivered", countUp: true },
          { value: "4.8★", label: "client satisfaction", countUp: true },
          { value: "95%", label: "client retention", countUp: true },
        ],
        cta: "Get these results",
      },
      {
        type: "clients",
        eyebrow: "Our clients",
        title: "Trusted by 120+ hotels & resorts",
        rows: [
          [
            { src: "/images/clients/arkaya.png", alt: "Arkaya" },
            { src: "/images/clients/wabi-sabi.jpg", alt: "Wabi Sabi" },
            { src: "/images/clients/naad-wellness.png", alt: "Naad Wellness" },
            { src: "/images/clients/park-cafe.png", alt: "Park Cafe" },
            { src: "/images/clients/chocolate-room.png", alt: "The Chocolate Room" },
            { src: "/images/clients/chefkenzo.png", alt: "Chef Kenzo" },
          ],
          [
            { src: "/images/clients/north-wind.png", alt: "North Wind" },
            { src: "/images/clients/corbett-the-grand.png", alt: "Corbett The Grand" },
            { src: "/images/clients/eastrenspice.webp", alt: "Eastern Spice" },
            { src: "/images/clients/hotel-green-castle.jpg", alt: "Hotel Green Castle" },
            { src: "/images/clients/eracamp.png", alt: "Era Camp" },
            { src: "/images/clients/spice-haven.png", alt: "Spice Haven" },
          ],
        ],
        cta: "Join them",
      },
    ],
    finalImage: "/images/photos/im2.webp",
  },
  {
    slug: "website-development",
    title: "Hotel Website Design & Development | Fielmente",
    description: "Hotel websites built to book direct, with the Eazotel booking engine. +30% direct reservations in 60 days.",
    waTopic: "Hotel Website Development",
    headerCta: "Free review",
    mobileCta: "Get free review",
    hero: {
      image: "/images/services/hotel-website-development.png",
      tag: "Website Design & Development",
      title: "Hotel websites built to ",
      titleAccent: "book direct.",
      subtitle: "Fast, beautiful, with the Eazotel booking engine built in.",
      chips: ["+30% direct reservations in 60 days", "Booking engine built in"],
      form: { title: "Get a free website review", button: "Review my website" },
    },
    sections: [
      BUSINESS_PARTNERS,
      {
        type: "gallery",
        tone: "alt",
        eyebrow: "Our work",
        title: "Sites we've built",
        layout: "three",
        items: [
          {
            src: "/images/sites/naturoville.png",
            alt: "Naturoville Wellness Resort website",
            caption: "Naturoville Wellness Resort",
            kind: "site",
          },
          {
            src: "/images/sites/opera-house.png",
            alt: "Opera House website",
            caption: "Opera House",
            kind: "site",
          },
          {
            src: "/images/sites/nature-on-the-rock.png",
            alt: "Nature on the Rocks website",
            caption: "Nature on the Rocks",
            kind: "site",
          },
        ],
        features: [
          { title: "Image-led design", text: "Sells the stay at a glance." },
          { title: "Booking & payments", text: "Commission-free, built in." },
          { title: "Fast & SEO-ready", text: "Built to rank." },
          { title: "Easy CMS", text: "Update offers yourself." },
        ],
        cta: "Review my website",
      },
      { type: "steps", cta: "Start with a free review" },
      {
        type: "stats",
        stats: [
          { value: "+30%", label: "direct reservations in 60 days", countUp: true },
          { value: "+38%", label: "avg. direct revenue lift", countUp: true },
          { value: "500+", label: "properties served", countUp: true },
          { value: "4.8★", label: "client satisfaction", countUp: true },
        ],
        cta: "Get these results",
      },
      {
        type: "clients",
        eyebrow: "Our clients",
        title: "Trusted by 120+ hotels & resorts",
        rows: [
          [
            { src: "/images/clients/naturoville.png", alt: "Naturoville" },
            { src: "/images/clients/opera-house.png", alt: "Opera House" },
            { src: "/images/clients/nature-on-the-rocks.webp", alt: "Nature on the Rocks" },
            { src: "/images/clients/arkaya.png", alt: "Arkaya" },
            { src: "/images/clients/wabi-sabi.jpg", alt: "Wabi Sabi" },
            { src: "/images/clients/nothern-nawab.webp", alt: "Northern Nawab" },
          ],
          [
            { src: "/images/clients/soni-arena-hotel.png", alt: "Soni Arena Hotel" },
            { src: "/images/clients/infinity.webp", alt: "Infinity" },
            { src: "/images/clients/hotel-green-castle.jpg", alt: "Hotel Green Castle" },
            { src: "/images/clients/riviera.jpg", alt: "Riviera" },
            { src: "/images/clients/chefkenzo.png", alt: "Chef Kenzo" },
            { src: "/images/clients/naad-wellness.png", alt: "Naad Wellness" },
          ],
        ],
        cta: "Join them",
      },
    ],
    finalImage: "/images/photos/hotel-2.webp",
  },
  {
    slug: "ota-management",
    title: "OTA Listing & Revenue Management for Hotels | Fielmente",
    description: "OTA listing, ranking and revenue management for hotels on Booking.com, Agoda, MakeMyTrip, Goibibo, Airbnb and Cleartrip.",
    waTopic: "OTA & Revenue Management",
    headerCta: "Free audit",
    mobileCta: "Get free audit",
    hero: {
      image: "/images/services/ota-management.png",
      tag: "OTA & Revenue Management",
      title: "Rank higher on every OTA. ",
      titleAccent: "Earn more per room.",
      subtitle: "Listings, ranking, rate parity and revenue management, done for you.",
      chips: ["+30–50% bookings", "Listings · Ranking · Revenue"],
      form: { title: "Get a free OTA audit", button: "Audit my listings" },
    },
    sections: [
      {
        type: "partners",
        label: "Platforms we manage",
        logos: [
          { src: "/images/partners/booking-com.png", alt: "Booking.com", height: 34 },
          { src: "/images/partners/agoda-logo.png", alt: "Agoda", height: 40 },
          { src: "/images/partners/makemytrip-logo.png", alt: "MakeMyTrip", height: 34 },
          { src: "/images/partners/goibibo-logo.png", alt: "Goibibo", height: 34 },
          { src: "/images/partners/airbnb-logo.png", alt: "Airbnb", height: 38 },
          { src: "/images/partners/cleartrip-logo.png", alt: "Cleartrip", height: 30 },
        ],
      },
      {
        type: "split",
        tone: "alt",
        image: { src: "/images/photos/hotel-2.webp", alt: "Booking on a tablet" },
        eyebrow: "What you get",
        title: "Everything your listings need",
        features: [
          { title: "Listing setup & content", text: "Complete on every channel." },
          { title: "Ranking & reviews", text: "Climb the results." },
          { title: "Rate parity", text: "Protect direct sales." },
          { title: "Revenue management", text: "The right rate, every night." },
        ],
        cta: "Audit my listings",
      },
      { type: "steps" },
      {
        type: "stats",
        stats: [
          { value: "30–50%", label: "booking growth", countUp: false },
          { value: "500+", label: "properties served", countUp: true },
          { value: "95%", label: "client retention", countUp: true },
          { value: "4.8★", label: "client satisfaction", countUp: true },
        ],
        cta: "Get these results",
      },
      {
        type: "clients",
        eyebrow: "Our clients",
        title: "Trusted by 120+ hotels & resorts",
        rows: [
          [
            { src: "/images/clients/arkaya.png", alt: "Arkaya" },
            { src: "/images/clients/wabi-sabi.jpg", alt: "Wabi Sabi" },
            { src: "/images/clients/corbett-the-grand.png", alt: "Corbett The Grand" },
            { src: "/images/clients/hotel-green-castle.jpg", alt: "Hotel Green Castle" },
            { src: "/images/clients/zionhotel.png", alt: "Zion Hotel" },
            { src: "/images/clients/mahabir-palace.png", alt: "Mahabir Palace" },
          ],
          [
            { src: "/images/clients/soni-arena-hotel.png", alt: "Soni Arena Hotel" },
            { src: "/images/clients/tulipinn.png", alt: "Tulip Inn" },
            { src: "/images/clients/season-suites.png", alt: "Season Suites" },
            { src: "/images/clients/north-wind.png", alt: "North Wind" },
            { src: "/images/clients/kumaon-bliss.jpg", alt: "Kumaon Bliss" },
            { src: "/images/clients/altin-stays.webp", alt: "Altin Stays" },
          ],
        ],
        cta: "Join them",
      },
    ],
    finalImage: "/images/photos/hotel-3.webp",
  },
  {
    slug: "restaurant",
    title: "Restaurant Marketing & Advertising Agency | Fielmente",
    description: "Restaurant and café marketing: Google & Meta Ads, Instagram, Google Maps, branding and online ordering. Free restaurant audit.",
    waTopic: "Restaurant Marketing",
    headerCta: "Free audit",
    mobileCta: "Get free audit",
    hero: {
      image: "/images/photos/people-taking-photos-food-1536x1024.webp",
      tag: "Restaurant Marketing Agency",
      title: "Fill every table, ",
      titleAccent: "every night.",
      subtitle: "Ads, Instagram, Google Maps and branding for restaurants, cafés and cloud kitchens.",
      chips: ["Restaurants · Cafés · Cloud kitchens", "Google & Meta Ads"],
      badges: [
        { src: "/images/partners/google-partner.png", alt: "Google Partner" },
        { src: "/images/partners/meta-business-partner.png", alt: "Meta Business Partner" },
      ],
      form: { title: "Get a free restaurant audit", button: "Get my free audit" },
    },
    sections: [
      BUSINESS_PARTNERS,
      {
        type: "gallery",
        eyebrow: "Every kind of F&B",
        title: "Restaurants, cafés, bars and cloud kitchens",
        layout: "default",
        items: [
          { src: "/images/photos/im1.webp", alt: "Restaurants", caption: "Restaurants" },
          { src: "/images/photos/im2.webp", alt: "Cafés", caption: "Cafés" },
          {
            src: "/images/photos/chefs-in-restaurant-kitchen.webp",
            alt: "Fine dining",
            caption: "Fine dining",
          },
          { src: "/images/photos/pizza-party.webp", alt: "Casual dining", caption: "Casual dining" },
        ],
        cta: "Get my free restaurant audit",
      },
      {
        type: "services",
        tone: "alt",
        eyebrow: "What we do",
        title: "Everything you need to fill tables",
        text: "Tap any service to get a free audit.",
        items: [
          {
            image: "/images/services/performance-marketing.png",
            title: "Google & Meta Ads",
            note: "Avg. 2.4× ROAS",
            muted: false,
          },
          {
            image: "/images/services/local-seo.png",
            title: "SEO & Google Maps",
            note: "Top 3 in 90 days (avg.)",
            muted: false,
          },
          {
            image: "/images/services/social-media-management.png",
            title: "Social Media & Content",
            note: "Reels, shoots, community",
            muted: true,
          },
          {
            image: "/images/sites/wabi-sabi.png",
            title: "Branding & Identity",
            note: "From logo to launch",
            muted: true,
          },
          {
            image: "/images/sites/aaoji.png",
            title: "Website & Online Ordering",
            note: "Menus, reservations, orders",
            muted: true,
          },
        ],
        eazotel: false,
      },
      {
        type: "gallery",
        tone: "alt",
        eyebrow: "Our work",
        title: "Restaurant sites we've built",
        layout: "three",
        items: [
          {
            src: "/images/sites/northern-nawab.png",
            alt: "Northern Nawab website",
            caption: "Northern Nawab",
            kind: "site",
          },
          { src: "/images/sites/moet.png", alt: "Moets website", caption: "Moets", kind: "site" },
          {
            src: "/images/sites/shreeiyengar.png",
            alt: "Shree Iyengar website",
            caption: "Shree Iyengar",
            kind: "site",
          },
        ],
        features: [
          { title: "Google & Meta Ads", text: "Footfall, orders and reservations." },
          { title: "Instagram & reels", text: "Food people want to share." },
          { title: "Google Maps", text: "Win “restaurants near me”." },
          { title: "Reviews", text: "More 5-star ratings." },
        ],
        cta: "Get more customers",
      },
      { type: "steps" },
      {
        type: "stats",
        stats: [
          { value: "500+", label: "brands since 2020", countUp: true },
          { value: "1,000+", label: "campaigns delivered", countUp: true },
          { value: "95%", label: "client retention", countUp: true },
          { value: "4.8★", label: "client satisfaction", countUp: true },
        ],
        cta: "Grow my restaurant",
      },
      {
        type: "clients",
        eyebrow: "Our clients",
        title: "Restaurants that grow with us",
        rows: [
          [
            { src: "/images/clients/park-cafe.png", alt: "Park Cafe" },
            { src: "/images/clients/chocolate-room.png", alt: "The Chocolate Room" },
            { src: "/images/clients/chefkenzo.png", alt: "Chef Kenzo" },
            { src: "/images/clients/eastrenspice.webp", alt: "Eastern Spice" },
          ],
          [
            { src: "/images/clients/spice-haven.png", alt: "Spice Haven" },
            { src: "/images/clients/petal-panyaram.png", alt: "Petals & Paniyaram" },
            { src: "/images/clients/nothern-nawab.webp", alt: "Northern Nawab" },
            { src: "/images/clients/opera-house.png", alt: "Opera House" },
          ],
        ],
        cta: "Join them",
      },
    ],
    finalImage: "/images/photos/im1.webp",
  },
  {
    slug: "wellness",
    title: "Wellness & Ayurveda Resort Marketing Agency | Fielmente",
    description: "Marketing for wellness, Ayurveda, yoga and detox retreats: Google Ads, SEO, websites and OTAs that bring direct bookings.",
    waTopic: "Wellness Resort Marketing",
    headerCta: "Free audit",
    mobileCta: "Get free audit",
    hero: {
      image: "/images/photos/im6.webp",
      tag: "Wellness & Ayurveda Marketing",
      title: "More bookings for ",
      titleAccent: "wellness & Ayurveda retreats.",
      subtitle: "Reach guests searching for Ayurveda, yoga, detox and spa stays.",
      chips: ["Ayurveda · Yoga · Detox · Spa", "Direct bookings"],
      form: { title: "Get a free wellness audit", button: "Get my free audit" },
    },
    sections: [
      BUSINESS_PARTNERS,
      {
        type: "gallery",
        tone: "alt",
        eyebrow: "Our work",
        title: "Wellness brands we grow",
        layout: "three",
        items: [
          {
            src: "/images/sites/naturoville.png",
            alt: "Naturoville Wellness Resort website",
            caption: "Naturoville Wellness Resort",
            kind: "site",
          },
          {
            src: "/images/sites/wabi-sabi.png",
            alt: "Wabi Sabi website",
            caption: "Wabi Sabi",
            kind: "site",
          },
          {
            src: "/images/sites/soul-stories.png",
            alt: "Soul Stories website",
            caption: "Soul Stories",
            kind: "site",
          },
        ],
        features: [
          { title: "Search ads", text: "Guests searching Ayurveda & detox." },
          { title: "SEO & content", text: "Rank for programmes & retreats." },
          { title: "Retreat packages", text: "Pages that sell multi-night stays." },
          { title: "Instagram", text: "Calm, aspirational content." },
        ],
        cta: "Get my free wellness audit",
      },
      {
        type: "services",
        tone: "alt",
        eyebrow: "What we do",
        title: "Everything you need to book direct",
        text: "Tap any service to get a free audit.",
        items: [
          {
            image: "/images/services/hotel-website-development.png",
            title: "Website & Booking Engine",
            note: "+30% direct reservations in 60 days",
            muted: false,
          },
          {
            image: "/images/services/performance-marketing.png",
            title: "Google & Meta Ads",
            note: "Avg. 2.4× ROAS",
            muted: false,
          },
          {
            image: "/images/services/seo-for-hotel.png",
            title: "SEO & Local SEO",
            note: "Top 3 in 90 days (avg.)",
            muted: false,
          },
          {
            image: "/images/services/social-media-management.png",
            title: "Social Media & Content",
            note: "Reels, shoots, community",
            muted: true,
          },
          {
            image: "/images/services/ota-management.png",
            title: "OTA Management",
            note: "Listings, parity, ranking",
            muted: true,
          },
        ],
        eazotel: true,
      },
      { type: "steps" },
      {
        type: "stats",
        stats: [
          { value: "500+", label: "properties served", countUp: true },
          { value: "+38%", label: "avg. direct revenue lift", countUp: true },
          { value: "95%", label: "client retention", countUp: true },
          { value: "4.8★", label: "client satisfaction", countUp: true },
        ],
        cta: "Grow my retreat",
      },
      {
        type: "clients",
        eyebrow: "Our clients",
        title: "Wellness & nature retreats that grow with us",
        rows: [
          [
            { src: "/images/clients/naad-wellness.png", alt: "Naad Wellness" },
            { src: "/images/clients/naturoville.png", alt: "Naturoville" },
            { src: "/images/clients/wabi-sabi.jpg", alt: "Wabi Sabi" },
            { src: "/images/clients/arkaya.png", alt: "Arkaya" },
          ],
          [
            { src: "/images/clients/north-wind.png", alt: "North Wind" },
            { src: "/images/clients/corbett-the-grand.png", alt: "Corbett The Grand" },
            { src: "/images/clients/kumaon-bliss.jpg", alt: "Kumaon Bliss" },
            { src: "/images/clients/nature-on-the-rocks.webp", alt: "Nature on the Rocks" },
          ],
        ],
        cta: "Join them",
      },
    ],
    finalImage: "/images/photos/im7.webp",
  },
  {
    slug: "branding",
    title: "Hotel & Restaurant Branding Agency in India | Fielmente",
    description: "Hotel, resort and restaurant branding: strategy, logo and identity, websites and launch. Brands guests remember and book.",
    waTopic: "Hotel & Restaurant Branding",
    headerCta: "Free review",
    mobileCta: "Get free review",
    hero: {
      image: "/images/services/about2.jpg",
      tag: "Hotel & Restaurant Branding",
      title: "Brands guests ",
      titleAccent: "remember and book.",
      subtitle: "Strategy, logo, identity, website and launch for hotels, resorts and restaurants.",
      chips: ["From logo to launch", "Hotels · Resorts · F&B"],
      form: { title: "Get a free brand review", button: "Review my brand" },
    },
    sections: [
      BUSINESS_PARTNERS,
      {
        type: "gallery",
        tone: "alt",
        eyebrow: "Our work",
        title: "Brands we've built",
        layout: "three",
        items: [
          {
            src: "/images/sites/wabi-sabi.png",
            alt: "Wabi Sabi website",
            caption: "Wabi Sabi",
            kind: "site",
          },
          { src: "/images/sites/moet.png", alt: "Moets website", caption: "Moets", kind: "site" },
          {
            src: "/images/sites/soul-stories.png",
            alt: "Soul Stories website",
            caption: "Soul Stories",
            kind: "site",
          },
        ],
        features: [
          { title: "Brand strategy", text: "Positioning guests remember." },
          { title: "Logo & identity", text: "Name, logo, colours, type." },
          { title: "Website & content", text: "Your brand, ready to book." },
          { title: "Launch", text: "Social, ads and PR from day one." },
        ],
        cta: "Review my brand",
      },
      { type: "steps", cta: "Start with a free review" },
      {
        type: "stats",
        stats: [
          { value: "500+", label: "brands since 2020", countUp: true },
          { value: "1,000+", label: "campaigns delivered", countUp: true },
          { value: "95%", label: "client retention", countUp: true },
          { value: "4.8★", label: "client satisfaction", countUp: true },
        ],
        cta: "Build my brand",
      },
      {
        type: "clients",
        eyebrow: "Our clients",
        title: "Brands that grow with us",
        rows: [
          [
            { src: "/images/clients/wabi-sabi.jpg", alt: "Wabi Sabi" },
            { src: "/images/clients/arkaya.png", alt: "Arkaya" },
            { src: "/images/clients/nothern-nawab.webp", alt: "Northern Nawab" },
            { src: "/images/clients/opera-house.png", alt: "Opera House" },
            { src: "/images/clients/park-cafe.png", alt: "Park Cafe" },
          ],
          [
            { src: "/images/clients/chefkenzo.png", alt: "Chef Kenzo" },
            { src: "/images/clients/naad-wellness.png", alt: "Naad Wellness" },
            { src: "/images/clients/nature-on-the-rocks.webp", alt: "Nature on the Rocks" },
            { src: "/images/clients/infinity.webp", alt: "Infinity" },
            { src: "/images/clients/riviera.jpg", alt: "Riviera" },
          ],
        ],
        cta: "Join them",
      },
    ],
    finalImage: "/images/services/about2.jpg",
  },
  {
    slug: "revenue-management",
    title: "Hotel Revenue Management Company in India | Fielmente",
    description: "Hotel revenue management: pricing, channel mix, OTA rates and rate parity, with weekly reports. Grow revenue per room.",
    waTopic: "Hotel Revenue Management",
    headerCta: "Free audit",
    mobileCta: "Get free audit",
    hero: {
      image: "/images/photos/planning-hotel-stay-on-laptop.webp",
      tag: "Hotel Revenue Management",
      title: "Sell every room at ",
      titleAccent: "the right rate.",
      subtitle: "Pricing, channel mix and OTA rates, managed every week.",
      chips: ["+30–50% bookings", "OTA & direct"],
      form: { title: "Get a free revenue audit", button: "Get my free audit" },
    },
    sections: [
      {
        type: "partners",
        label: "Channels we manage",
        logos: [
          { src: "/images/partners/booking-com.png", alt: "Booking.com", height: 34 },
          { src: "/images/partners/agoda-logo.png", alt: "Agoda", height: 40 },
          { src: "/images/partners/makemytrip-logo.png", alt: "MakeMyTrip", height: 34 },
          { src: "/images/partners/goibibo-logo.png", alt: "Goibibo", height: 34 },
          { src: "/images/partners/airbnb-logo.png", alt: "Airbnb", height: 38 },
          { src: "/images/partners/cleartrip-logo.png", alt: "Cleartrip", height: 30 },
        ],
      },
      {
        type: "split",
        tone: "alt",
        image: { src: "/images/photos/grilwithchart.webp", alt: "Revenue dashboard" },
        eyebrow: "What you get",
        title: "More revenue from every room",
        features: [
          { title: "Pricing strategy", text: "Rates by day, season and demand." },
          { title: "Channel mix", text: "The right OTAs, more direct." },
          { title: "Rate parity", text: "Protect direct sales." },
          { title: "Weekly reports", text: "Occupancy, ADR and RevPAR." },
        ],
        cta: "Get my free revenue audit",
      },
      {
        type: "services",
        tone: "alt",
        eyebrow: "What we do",
        title: "Revenue plus the demand to fill it",
        text: "Tap any service to get a free audit.",
        items: [
          {
            image: "/images/services/ota-management.png",
            title: "OTA Management",
            note: "Listings, parity, ranking",
            muted: true,
          },
          {
            image: "/images/services/hotel-website-development.png",
            title: "Website & Booking Engine",
            note: "+30% direct reservations in 60 days",
            muted: false,
          },
          {
            image: "/images/services/performance-marketing.png",
            title: "Google & Meta Ads",
            note: "Avg. 2.4× ROAS",
            muted: false,
          },
          {
            image: "/images/photos/built-ai.png",
            title: "WhatsApp AI & Hotel CRM",
            note: "Every enquiry answered 24/7",
            muted: true,
          },
        ],
        eazotel: true,
      },
      { type: "steps" },
      {
        type: "stats",
        stats: [
          { value: "30–50%", label: "booking growth", countUp: false },
          { value: "+38%", label: "avg. direct revenue lift", countUp: true },
          { value: "500+", label: "properties served", countUp: true },
          { value: "95%", label: "client retention", countUp: true },
        ],
        cta: "Grow my revenue",
      },
      {
        type: "clients",
        eyebrow: "Our clients",
        title: "Trusted by 120+ hotels & resorts",
        rows: [
          [
            { src: "/images/clients/arkaya.png", alt: "Arkaya" },
            { src: "/images/clients/wabi-sabi.jpg", alt: "Wabi Sabi" },
            { src: "/images/clients/naad-wellness.png", alt: "Naad Wellness" },
            { src: "/images/clients/corbett-the-grand.png", alt: "Corbett The Grand" },
            { src: "/images/clients/north-wind.png", alt: "North Wind" },
            { src: "/images/clients/naturoville.png", alt: "Naturoville" },
          ],
          [
            { src: "/images/clients/hotel-green-castle.jpg", alt: "Hotel Green Castle" },
            { src: "/images/clients/zionhotel.png", alt: "Zion Hotel" },
            { src: "/images/clients/mahabir-palace.png", alt: "Mahabir Palace" },
            { src: "/images/clients/soni-arena-hotel.png", alt: "Soni Arena Hotel" },
            { src: "/images/clients/kumaon-bliss.jpg", alt: "Kumaon Bliss" },
            { src: "/images/clients/colonels-resort.png", alt: "Colonel's Resort" },
          ],
        ],
        cta: "Join them",
      },
    ],
    finalImage: "/images/photos/hotel-3.webp",
  },
  {
    slug: "hotel-crm",
    title: "Hotel CRM & WhatsApp AI Sales Agent | Eazotel by Fielmente",
    description: "Capture Google, Meta and WhatsApp leads in one hotel CRM. An AI agent answers enquiries 24/7 and turns them into direct bookings.",
    waTopic: "Hotel CRM & WhatsApp AI",
    headerCta: "Free demo",
    mobileCta: "Book free demo",
    hero: {
      image: "/images/photos/portrait-happy-smiling-bellboy.jpg",
      tag: "Hotel CRM & WhatsApp AI",
      title: "Never lose a guest ",
      titleAccent: "enquiry again.",
      subtitle: "Google, Meta and WhatsApp leads in one CRM, with an AI agent that replies 24/7.",
      chips: ["Powered by Eazotel", "WhatsApp AI agent"],
      form: { title: "Book a free demo", button: "Book my free demo" },
    },
    sections: [
      BUSINESS_PARTNERS,
      {
        type: "split",
        tone: "alt",
        image: { src: "/images/photos/built-ai.png", alt: "AI chat on a laptop" },
        eyebrow: "What you get",
        title: "One CRM for every guest lead",
        features: [
          { title: "Every lead, one inbox", text: "Google, Meta, WhatsApp & website." },
          { title: "AI WhatsApp agent", text: "Replies and quotes 24/7." },
          { title: "Auto follow-ups", text: "No enquiry goes cold." },
          { title: "Booking & payments", text: "Turn chats into direct bookings." },
        ],
        cta: "Book my free demo",
      },
      {
        type: "gallery",
        eyebrow: "Built for hotels",
        title: "From first message to checked-in guest",
        layout: "default",
        items: [
          { src: "/images/photos/hotel-receptionist-check.png", alt: "Front desk", caption: "Front desk" },
          { src: "/images/photos/hotel-4.webp", alt: "Sales team", caption: "Sales team" },
          {
            src: "/images/photos/mobile-screen-frame-collage-768x1097.webp",
            alt: "WhatsApp",
            caption: "WhatsApp",
          },
          { src: "/images/photos/hotel-2.webp", alt: "Direct bookings", caption: "Direct bookings" },
        ],
        cta: "See it in a demo",
      },
      { type: "steps", cta: "Start with a free demo" },
      {
        type: "clients",
        eyebrow: "Our clients",
        title: "Used by hotels & resorts across India",
        rows: [
          [
            { src: "/images/clients/arkaya.png", alt: "Arkaya" },
            { src: "/images/clients/wabi-sabi.jpg", alt: "Wabi Sabi" },
            { src: "/images/clients/naad-wellness.png", alt: "Naad Wellness" },
            { src: "/images/clients/corbett-the-grand.png", alt: "Corbett The Grand" },
            { src: "/images/clients/north-wind.png", alt: "North Wind" },
            { src: "/images/clients/naturoville.png", alt: "Naturoville" },
          ],
          [
            { src: "/images/clients/hotel-green-castle.jpg", alt: "Hotel Green Castle" },
            { src: "/images/clients/zionhotel.png", alt: "Zion Hotel" },
            { src: "/images/clients/mahabir-palace.png", alt: "Mahabir Palace" },
            { src: "/images/clients/soni-arena-hotel.png", alt: "Soni Arena Hotel" },
            { src: "/images/clients/kumaon-bliss.jpg", alt: "Kumaon Bliss" },
            { src: "/images/clients/colonels-resort.png", alt: "Colonel's Resort" },
          ],
        ],
        cta: "Book my free demo",
      },
    ],
    finalImage: "/images/photos/hotel-4.webp",
  },
];

export function getPage(slug: string): LandingPage | undefined {
  return pages.find((page) => page.slug === slug);
}
